######################################################################
# Automatically generated by qmake (2.01a) ? 8? 17 23:43:13 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/dir.h src/effect.h src/resize.h src/window.h
SOURCES += src/dir.cpp src/effect.cpp src/main.cpp src/resize.cpp src/window.cpp
