#############################################################################
# Makefile for building: imgeffect
# Generated by qmake (2.01a) (Qt 4.7.2) on: ? 12? 6 15:38:00 2012
# Project:  imgeffect.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile imgeffect.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -m32 -march=i686 -mtune=generic -fasynchronous-unwind-tables -fno-strict-aliasing -fno-schedule-insns2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -m32 -march=i686 -mtune=generic -fasynchronous-unwind-tables -fno-strict-aliasing -fno-schedule-insns2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt-4.7.2/mkspecs/linux-g++ -I. -I/usr/lib/qt-4.7.2/include/QtCore -I/usr/lib/qt-4.7.2/include/QtGui -I/usr/lib/qt-4.7.2/include -I. -Isrc -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/qt-4.7.2/lib -lQtGui -L/usr/lib/qt-4.7.2/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/dir.cpp \
		src/effect.cpp \
		src/main.cpp \
		src/resize.cpp \
		src/window.cpp moc_window.cpp
OBJECTS       = dir.o \
		effect.o \
		main.o \
		resize.o \
		window.o \
		moc_window.o
DIST          = /usr/lib/qt-4.7.2/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt-4.7.2/mkspecs/common/unix.conf \
		/usr/lib/qt-4.7.2/mkspecs/common/linux.conf \
		/usr/lib/qt-4.7.2/mkspecs/qconfig.pri \
		/usr/lib/qt-4.7.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt-4.7.2/mkspecs/features/qt_functions.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/qt_config.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/default_pre.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/release.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/default_post.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/warn_on.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/qt.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/unix/thread.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/moc.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/resources.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/uic.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/yacc.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/lex.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/include_source_dir.prf \
		imgeffect.pro
QMAKE_TARGET  = imgeffect
DESTDIR       = 
TARGET        = imgeffect

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: imgeffect.pro  /usr/lib/qt-4.7.2/mkspecs/linux-g++/qmake.conf /usr/lib/qt-4.7.2/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt-4.7.2/mkspecs/common/unix.conf \
		/usr/lib/qt-4.7.2/mkspecs/common/linux.conf \
		/usr/lib/qt-4.7.2/mkspecs/qconfig.pri \
		/usr/lib/qt-4.7.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt-4.7.2/mkspecs/features/qt_functions.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/qt_config.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/default_pre.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/release.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/default_post.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/warn_on.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/qt.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/unix/thread.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/moc.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/resources.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/uic.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/yacc.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/lex.prf \
		/usr/lib/qt-4.7.2/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt-4.7.2/lib/libQtGui.prl \
		/usr/lib/qt-4.7.2/lib/libQtCore.prl
	$(QMAKE) -o Makefile imgeffect.pro
/usr/lib/qt-4.7.2/mkspecs/common/g++-multilib.conf:
/usr/lib/qt-4.7.2/mkspecs/common/unix.conf:
/usr/lib/qt-4.7.2/mkspecs/common/linux.conf:
/usr/lib/qt-4.7.2/mkspecs/qconfig.pri:
/usr/lib/qt-4.7.2/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt-4.7.2/mkspecs/features/qt_functions.prf:
/usr/lib/qt-4.7.2/mkspecs/features/qt_config.prf:
/usr/lib/qt-4.7.2/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt-4.7.2/mkspecs/features/default_pre.prf:
/usr/lib/qt-4.7.2/mkspecs/features/release.prf:
/usr/lib/qt-4.7.2/mkspecs/features/default_post.prf:
/usr/lib/qt-4.7.2/mkspecs/features/warn_on.prf:
/usr/lib/qt-4.7.2/mkspecs/features/qt.prf:
/usr/lib/qt-4.7.2/mkspecs/features/unix/thread.prf:
/usr/lib/qt-4.7.2/mkspecs/features/moc.prf:
/usr/lib/qt-4.7.2/mkspecs/features/resources.prf:
/usr/lib/qt-4.7.2/mkspecs/features/uic.prf:
/usr/lib/qt-4.7.2/mkspecs/features/yacc.prf:
/usr/lib/qt-4.7.2/mkspecs/features/lex.prf:
/usr/lib/qt-4.7.2/mkspecs/features/include_source_dir.prf:
/usr/lib/qt-4.7.2/lib/libQtGui.prl:
/usr/lib/qt-4.7.2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile imgeffect.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/imgeffect1.0.0 || $(MKDIR) .tmp/imgeffect1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/imgeffect1.0.0/ && $(COPY_FILE) --parents src/dir.h src/effect.h src/resize.h src/window.h .tmp/imgeffect1.0.0/ && $(COPY_FILE) --parents src/dir.cpp src/effect.cpp src/main.cpp src/resize.cpp src/window.cpp .tmp/imgeffect1.0.0/ && (cd `dirname .tmp/imgeffect1.0.0` && $(TAR) imgeffect1.0.0.tar imgeffect1.0.0 && $(COMPRESS) imgeffect1.0.0.tar) && $(MOVE) `dirname .tmp/imgeffect1.0.0`/imgeffect1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/imgeffect1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp
moc_window.cpp: src/window.h
	/usr/lib/qt-4.7.2/bin/moc $(DEFINES) $(INCPATH) src/window.h -o moc_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

dir.o: src/dir.cpp src/dir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dir.o src/dir.cpp

effect.o: src/effect.cpp src/effect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o effect.o src/effect.cpp

main.o: src/main.cpp src/window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

resize.o: src/resize.cpp src/resize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resize.o src/resize.cpp

window.o: src/window.cpp src/window.h \
		src/resize.h \
		src/dir.h \
		src/effect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o src/window.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

